---
title: "Assignment 2"
author: "Huy Nguyen"
date: "24/01/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Problem 1

``` {r, echo = FALSE}
radius = c(1,3,5,7)
volume = 4/3*pi*radius^3

par(mfrow = c(2, 2))

plot(radius, volume, main = "Line ('l)' Plot of a Sphere's Volume", xlab = "Radius", ylab = "Volume", ylim = c(0,1500), xlim = c(-1,9), col = "blue", lwd = 2, type = "l", lty = 1, cex = 0.5, cex.main = 0.9)

plot(radius, volume, main = "Points ('p') Plot of a Sphere's Volume", xlab = "Radius", ylab = "Volume", ylim = c(0,1500), xlim = c(-1,9), col = "red", lwd = 3, type = "p", lty = 1, cex = 0.5, cex.main = 0.9)

plot(radius, volume, main = "Empty Plot ('n') of a Sphere's Volume", xlab = "Radius", ylab = "Volume", ylim = c(0,1500), xlim = c(-1,9), col = "green", lwd = 1.5, type = "n", lty = 2, cex = 0.5, cex.main = 0.9)

plot(radius, volume, main = "Line and Points ('b') Plot of a Sphere's Volume", xlab = "Radius", ylab = "Volume", ylim = c(0,1500), xlim = c(-1,9), col = "orange", lwd = 2.5, type = "b", lty = 1, cex = 0.1, cex.main = 0.9)

```
